version: '3.8'

services:
  # Laravel App with PHP-FPM (Classic Stack)
  classic-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-classic-app
    container_name: laravel_classic_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=classic-mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - REDIS_HOST=classic-redis
      - REDIS_PORT=6379
    depends_on:
      - classic-mysql
      - classic-redis
    networks:
      - laravel-classic

  # Nginx Web Server (Classic Stack)
  classic-nginx:
    image: nginx:alpine
    container_name: laravel_classic_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - classic-app
    networks:
      - laravel-classic

  # MySQL Database (Classic Stack)
  classic-mysql:
    image: mysql:8.0
    container_name: laravel_classic_mysql
    restart: unless-stopped
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_classic_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel-classic

  # Redis Cache (Classic Stack)
  classic-redis:
    image: redis:7-alpine
    container_name: laravel_classic_redis
    restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      - redis_classic_data:/data
    command: redis-server --appendonly yes
    networks:
      - laravel-classic

  # phpMyAdmin (Classic Stack)
  classic-phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_classic_phpmyadmin
    restart: unless-stopped
    ports:
      - "8071:80"
    environment:
      PMA_HOST: classic-mysql
      PMA_USER: laravel
      PMA_PASSWORD: secret
    depends_on:
      - classic-mysql
    networks:
      - laravel-classic

# Networks
networks:
  laravel-classic:
    driver: bridge

# Volumes
volumes:
  mysql_classic_data:
    driver: local
  redis_classic_data:
    driver: local 